name: flutter_mrz_scanner_enhanced_example
description: Demonstrates how to use the flutter_mrz_scanner_enhanced plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_mrz_scanner_enhanced:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
